import Thoughts from '@/components/Thoughts'
import { db } from '@/utils/Firebase'
import { collection, onSnapshot, orderBy, query } from 'firebase/firestore'
import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'

export default function Home() {

  // State for All Posts
  const [allPosts, setAllPosts] = useState([])

  const getPost = async () => {
    const collectionRef = collection(db, "socialApp-Posts");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    const snap = onSnapshot(q, (snapshot) => {
      setAllPosts(snapshot.docs.map((doc)=> ({ ...doc.data(), id: doc.id})))
    })
  }


  useEffect(() => {
    getPost();
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-12 text-lg font-medium'>
        <h2 className="" >Other People's Thoughts</h2>

        {allPosts.map(post => (<Thoughts {...post} key={post.id} > 
        
        <Link href={{pathname: `/${post.id}`, query:{...post}}}>
          <button>
            {post.commentContent?.length} comments
          </button>
        </Link>
        </Thoughts>))}

      </div>
      
    </>
  )
}
